frase = 'Curso em Vídeo Python'
frase2 = '   Espaços no início e no fim   '
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[1:14])
print(frase[1:14:2])
print(frase[::2])
print(frase.count('o'))
print(frase.upper())
print(frase.upper().count('O'))
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(len(frase))
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())
print('Curso' in frase)
print(frase.find('em'))
print(frase.find('EM'))
print(frase.upper().find('EM'))
print(frase.split())
dividido = frase.split()
print(dividido[2][2])
