n1 = input('Digite um valor: ')
n2 = str(n1)
n3 = int(n1)
n4 = float(n1)
n5 = bool(n1)
print(n1)
print(type(n1))
print(n1.isalnum())
print(n1.isalpha())
print(n1.isascii())
print(n1.isdecimal())
print(n1.isdigit())
print(n1.isidentifier())
print(n1.islower())
print(n1.isnumeric())
print(n1.isprintable())
print(n1.isspace())
print(n1.istitle())
print(n1.isupper())
print(n2)
print(type(n2))
print(n2.isalnum())
print(n2.isalpha())
print(n2.isascii())
print(n2.isdecimal())
print(n2.isdigit())
print(n2.isidentifier())
print(n2.islower())
print(n2.isnumeric())
print(n2.isprintable())
print(n2.isspace())
print(n2.istitle())
print(n2.isupper())
print(n3)
print(type(n3))
print(n3.as_integer_ratio())
print(n3.bit_length())
print(n3.conjugate())

print(n4)
print(type(n4))
print(n5)
print(type(n5))