n1 = input('Digite um valor: ')
n2 = str(input('Digite um valor: '))
# n3 = int(input('Digite um número inteiro'))
# n4 = float(input('Digite um número'))
# n5 = bool(n1)
print('PROPRIEDADES DA VARIÁVEL N1 STR')
print(n1)
# Verifica o tipo primitivo da variável
print(type(n1))
print('É Alphanumérico?', n1.isalnum())
print('É Alfabético?', n1.isalpha())
print('É um Caractere ASCII?', n1.isascii())
print('É Decimal?', n1.isdecimal())
print('É um Dígito?', n1.isdigit())
print('É Identificador?', n1.isidentifier())
print('Todos os caracteres são Minúsculos? ', n1.islower())
print('É Numérico?', n1.isnumeric())
print('É Printável?', n1.isprintable())
print('É um Espaço?', n1.isspace())
print('A primeira letra de cada palávra é maiúscula?', n1.istitle())
print('Todos os caracteres são Maiúsculos?', n1.isupper())
print('PROPRIEDADES DA VARIÁVEL N2 STR')
print(n2)
# Verifica o tipo primitivo da variável
print(type(n2))
print('É Alphanumérico?', n2.isalnum())
print('É Alfabético?', n2.isalpha())
print('É um Caractere ASCII?', n2.isascii())
print('É Decimal?', n2.isdecimal())
print('É um Dígito?', n2.isdigit())
print('É Identificador?', n2.isidentifier())
print('Todos os caracteres são Minúsculos? ', n2.islower())
print('É Numérico?', n2.isnumeric())
print('É Printável?', n2.isprintable())
print('É um Espaço?', n2.isspace())
print('A primeira letra de cada palávra é maiúscula?', n2.istitle())
print('Todos os caracteres são Maiúsculos?', n2.isupper())
"""print('PROPRIEDADES DA VARIÁVEL N3 INT')
print(n3)
print(type(n3))
print(n3.as_integer_ratio())
print(n3.bit_length())
print(n3.conjugate())
print(n4)
print('PROPRIEDADES DA VARIÁVEL N4 FLOAT')
print(type(n4))
print('PROPRIEDADES DA VARIÁVEL N5 BOLL')
print(n5)
print(type(n5))"""
